### ISSUE TITLE
Track File Request

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-secure-storage#2]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Add Log-Entry, when base file gets requested

```yaml
secure_storage:
    pimcore_asset_protection:
        track_asset_request: true
```
